C-----------------------------------------------------------------------
C HEADER FOR COMMUNICATIONS
C-----------------------------------------------------------------------

C COMMUNICATION TYPES








C - NOT SURE WE WANT ALL THESE!!!

      integer   SYNC_VALUE
      integer   TERMINATION_SIG
      integer   num_sr_type

      parameter (SYNC_VALUE      = -1)
      parameter (TERMINATION_SIG = -1)
      parameter (num_sr_type     =  4)

