C-----------------------------------------------------------------------
C PARAMETERS FOR LES PROGRAM
C-----------------------------------------------------------------------

C SOLUTION VARIABLES

      integer   SV_U
      integer   SV_V
      integer   SV_W
      integer   SV_P
      integer   SV_SC1

      parameter (SV_U  =  1)
      parameter (SV_V  =  2)
      parameter (SV_W  =  3)
      parameter (SV_P  =  4)
      parameter (SV_SC1  =  5)

