C-----------------------------------------------------------------------
C COMMON BLOCK FOR GLOBAL GRID PARAMETERS
C-----------------------------------------------------------------------

C - ORGANIZED LIKE THIS FOR EASE OF USE RATHER THAN

C-----------------------------------------------------------------------
C GLOBAL GRID PARAMETERS DATA
C-----------------------------------------------------------------------


C COMMON
      
      integer           radius
      common / cbgridp1 / radius

      real              ry0
      common / cbgridp2 / ry0

      logical           gotrad
      common / cbgridp3 / gotrad

